language: generic 

services:
    - docker

before_install:
    - docker build -t ramicorcorbalan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramicorcorbalan/docker-react npm run test