language: generic 

services:
    - docker

before_install:
    - docker build -t ramicorcorbalan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramicorcorbalan/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bocket_name: "elasticbeanstalk-us-east-2-551864635710"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY